version: "3.7"

services:
    postgres:
        image: postgres:16
        restart: unless-stopped
        environment:
            POSTGRES_DB: n8n
            POSTGRES_USER: n8n
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        volumes:
            - pg_data:/var/lib/postgresql/data

    n8n:
        image: docker.n8n.io/n8nio/n8n
        container_name: n8n
        ports:
            - "5678:5678"
        restart: unless-stopped
        environment:
            DB_TYPE: postgresdb
            DB_POSTGRESDB_DATABASE: n8n
            DB_POSTGRESDB_HOST: postgres
            DB_POSTGRESDB_PORT: 5432
            DB_POSTGRESDB_USER: n8n
            DB_POSTGRESDB_PASSWORD: ${POSTGRES_PASSWORD}
            DB_POSTGRESDB_SCHEMA: public
            N8N_PORT: 5678
            N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: "true"
        volumes:
            - n8n_data:/home/node/.n8n

volumes:
    pg_data:
    n8n_data:
